'use strict';
const $ = id => document.getElementById(id);
const frame = $('comparison');
let jobs = [], installation = null;
const names = {companion:'Companion',compare:'Compare Runs',settings:'Settings',tune:'Tune Model',code:'Explore Code',scenario:'Create Scenario'};
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function status(error){$('shellStatus').textContent=error?error.message:'';}
function navigate(view){const target=['companion','compare','settings'].includes(view)?view:'unavailable';for(const id of ['companion','compare','settings','unavailable'])$(id+'View').classList.toggle('hidden',id!==target);$('viewTitle').textContent=names[view];$('newChat').classList.toggle('hidden',view!=='companion');document.querySelector('[data-view="companion"]').classList.toggle('active',view==='companion');$('unavailableTitle').textContent=names[view];}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>navigate(button.dataset.view));
document.querySelectorAll('[data-prompt]').forEach(button=>button.onclick=()=>{$('prompt').value=button.dataset.prompt;$('prompt').focus();});
function message(content,reply=false){const element=document.createElement('div');element.className='message'+(reply?' reply':'');element.textContent=content;$('messages').append(element);$('welcome').classList.add('hidden');$('messages').classList.remove('hidden');element.scrollIntoView({block:'nearest'});return element;}
function action(parent,label,callback){const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=callback;parent.append(button);}
$('composer').onsubmit=event=>{event.preventDefault();const prompt=$('prompt').value.trim();if(!prompt)return;message(prompt);$('prompt').value='';if(/compar|runfiles?|run\.db/i.test(prompt)){const reply=message('Open Compare Runs to select the two runfiles, variables, and tolerances. The comparison uses the existing IFs model-vetting engine.',true);action(reply,'Open Compare Runs',()=>navigate('compare'));}else{message('AI is not connected yet, so I cannot interpret model questions or generate scenarios. You can use Compare Runs directly from Tools.',true);}};
$('newChat').onclick=()=>{$('messages').replaceChildren();$('messages').classList.add('hidden');$('welcome').classList.remove('hidden');$('prompt').value='';navigate('companion');};
// Expansion preferences survive the randomly assigned local engine port.
async function preferences(){try{const data=await api('/api/ui-preferences');for(const id of ['toolsGroup','recentGroup'])$(id).open=Boolean(data[id]);}catch(error){status(error);}for(const id of ['toolsGroup','recentGroup'])$(id).addEventListener('toggle',()=>{api('/api/ui-preferences',{toolsGroup:$('toolsGroup').open,recentGroup:$('recentGroup').open}).catch(status);});}
function applyInstallation(data){installation=data;$('installation').value=data.installation||'';$('installationLabel').textContent=data.installation?'IFs · '+data.installation.split(/[/\\]/).pop():'No IFs installation selected';$('settingsStatus').textContent=data.installation?data.runs.length+' supported runfiles found.':'Choose the folder containing DATA and RUNFILES.';}
$('saveInstallation').onclick=async()=>{const button=$('saveInstallation');button.disabled=true;try{const data=await api('/api/installation',{installation:$('installation').value});applyInstallation(data);if(frame.contentWindow.applyInstallation)frame.contentWindow.applyInstallation(data);status(null);}catch(error){$('settingsStatus').textContent=error.message;}finally{button.disabled=false;}};
$('browse').onclick=async()=>{try{const data=await api('/api/select-installation',{installation:$('installation').value});if(data.installation){$('installation').value=data.installation;await $('saveInstallation').onclick();}}catch(error){$('settingsStatus').textContent=error.message;}};
async function openRecent(id){try{const running=jobs.find(j=>j.status==='running');if(running&&running.id!==id){status(Error('A comparison is running. Wait for it to finish before opening a different report.'));return;}const win=frame.contentWindow;if(!win.openCompanionReport)throw Error('Compare Runs is still loading. Please try again.');await win.openCompanionReport(id);navigate('compare');status(null);}catch(error){status(error);}}
async function refreshRecent(){try{const data=await api('/api/recent');jobs=data.jobs;$('recent').replaceChildren();$('running').textContent=jobs.some(j=>j.status==='running')?'1 running':'';if(!jobs.length)$('recent').textContent='No comparisons yet.';for(const item of jobs){const button=document.createElement('button');button.textContent=item.title;const note=document.createElement('small');note.textContent=item.status+(item.created?' · '+new Date(item.created*1000).toLocaleDateString():'');button.append(note);button.onclick=()=>openRecent(item.id);$('recent').append(button);}}catch(error){status(error);}}
frame.addEventListener('load',()=>{const win=frame.contentWindow;const link=win.document.getElementById('openSettings');if(link)link.onclick=()=>navigate('settings');});
api('/api/installation').then(applyInstallation).catch(error=>{$('settingsStatus').textContent=error.message;status(error);});preferences();refreshRecent();setInterval(refreshRecent,3000);
